Food.create(name: 'banana', calories: 150)
Food.create(name: 'apple', calories: 100)
Food.create(name: 'toast', calories: 75)
Food.create(name: 'strawberries', calories: 200)
meal1 = Meal.create(name: 'breakfast')
meal2 = Meal.create(name: 'lunch')
meal3 = Meal.create(name: 'dinner')
meal1.meal_foods.create(food_id: 1)
meal1.meal_foods.create(food_id: 2)
meal2.meal_foods.create(food_id: 2)
meal2.meal_foods.create(food_id: 3)
meal2.meal_foods.create(food_id: 4)
meal3.meal_foods.create(food_id: 1)
meal3.meal_foods.create(food_id: 2)
meal3.meal_foods.create(food_id: 4)